"""Update KeywordPosition model

Revision ID: 06a7fa71759c
Revises: 4d0c8ed205ba
Create Date: 2024-12-27 17:44:10.512113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06a7fa71759c'
down_revision = '4d0c8ed205ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webmaster_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('check_date',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_position', schema=None) as batch_op:
        batch_op.alter_column('check_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('webmaster_date')

    # ### end Alembic commands ###
