"""Add webmaster_host_id to Project

Revision ID: 40e29184ee43
Revises: 3a4efe6df9e1
Create Date: 2024-12-27 18:12:57.425000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e29184ee43'
down_revision = '3a4efe6df9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем колонку как nullable
    op.add_column('project', sa.Column('yandex_webmaster_host_id', sa.String(length=50), nullable=True))
    
    # Обновляем существующие записи
    op.execute("UPDATE project SET yandex_webmaster_host_id = yandex_webmaster_host")
    
    # Делаем колонку not nullable
    op.alter_column('project', 'yandex_webmaster_host_id',
                    existing_type=sa.String(length=50),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'yandex_webmaster_host_id')
    # ### end Alembic commands ###
