"""Add last update fields

Revision ID: 4d0c8ed205ba
Revises: 1b16e0e8721c
Create Date: 2024-12-27 17:34:29.862880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0c8ed205ba'
down_revision = '1b16e0e8721c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_webmaster_update', sa.DateTime(), nullable=True))

    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_metrika_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_column('last_metrika_update')

    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.drop_column('last_webmaster_update')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
