"""Add Yandex.Metrika fields to Project model

Revision ID: 6f4b42656a5a
Revises: 1dad79c834ba
Create Date: 2024-12-29 22:26:51.087073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4b42656a5a'
down_revision = '1dad79c834ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yandex_metrika_counter', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('yandex_metrika_token', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('yandex_metrika_token')
        batch_op.drop_column('yandex_metrika_counter')

    # ### end Alembic commands ###
