"""Update models with region relationship

Revision ID: 7669633aad3d
Revises: 
Create Date: 2024-12-29 21:17:29.773671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7669633aad3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
