"""Add url_id to Keyword model

Revision ID: a3d31a6119c8
Revises: 2a2b64f35dd1
Create Date: 2024-12-30 09:50:02.279400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d31a6119c8'
down_revision = '2a2b64f35dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'url', ['url_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('url_id')

    # ### end Alembic commands ###
