"""Add data_date to KeywordPosition

Revision ID: e566ce21a34b
Revises: update_host_ids
Create Date: 2024-12-27 22:42:49.505981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e566ce21a34b'
down_revision = 'update_host_ids'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    with op.batch_alter_table('keyword_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('check_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('webmaster_date')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('yandex_webmaster_host_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yandex_webmaster_host_id', mysql.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('keyword_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webmaster_date', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('check_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('data_date')

    op.create_table('task',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('progress', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('result_url', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='task_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
